### ISSUE TITLE
Monerujo issue

### ISSUE THREAD

**Issue by T81** [LedgerHQ/ledger-app-monero#26]
Attaching the wallet on phone it prompts to open monerujo. Clicking the "+" icon it prompts to restore ledget wallet but when opening monero app in device, it disconnects and no longer recognized from smartphone.

Samsung Galaxy S6 Edge
Android 7.0

This issue is discussed also here: 
https://www.reddit.com/r/Monero/comments/96g6a5/monerujo_ledger_nano_s_issue

**Comment by cslashm** [comment]
stiil pending?

**Comment by T81** [comment]
Any updates?

**Comment by cslashm** [comment]
I do not manage Monerujo. I think it is better to contact the Monerujo dev.

**Comment by T81** [comment]
This is what monerujo dev told me too...

**Comment by cslashm** [comment]
Hmmm.... I will have a look

**Comment by Loyddjf** [comment]
Hello? Did Marujo solve the problem with the Ledger wallet? I still can't configure my device. I click + and not display Ledger.

**Comment by pricead** [comment]
Monerujo works fine with Ledger. Make sure both your XMR app on your device and Monerujo app are fully up to date. (you might need to remove your existing XMR app in Ledger Live and reinstall it - also make sure your Ledger device's firmware is fully updated)

**Comment by Loyddjf** [comment]
> Monerujo funciona bem com Ledger. Verifique se o aplicativo XMR no dispositivo e o aplicativo Monerujo estão totalmente atualizados. (pode ser necessário remover o aplicativo XMR existente no Ledger Live e reinstalá-lo - verifique também se o firmware do dispositivo Ledger está totalmente atualizado)

Does my Ledger 1.5.5 firmware need to upgrade to 1.6.0 to work? My monerujo app is updated v.1.12.11. I usually connect with the Ledger Live app on my Moto G6 Play Smartphone

**Comment by pricead** [comment]
I would recommend updating the firmware on the Nano S to 1.6, and then installing the latest Monero app to the Ledger device.

**Comment by Loyddjf** [comment]
> I would recommend updating the firmware on the Nano S to 1.6, and then installing the latest Monero app to the Ledger device.

Upgrade to firmware 1.6.0 on Ledger and ready it worked. thank you for help-me.
