### ISSUE TITLE
Lost my XMR

### ISSUE THREAD

**Issue by challal** [LedgerHQ/ledger-app-monero#28]
Hello,

I have problem after restore my Ledger i get all my coin only lost my XMR

Every time i reinstall monero app i get new monero address haw can restore first address or my first balance with my ledger seed

 And this 25 words in monero app not show i send here some image

![img_3816](https://user-images.githubusercontent.com/16299010/50718720-7f5f6400-108a-11e9-8791-95602b93e6bb.jpg)
![img_3815](https://user-images.githubusercontent.com/16299010/50718721-7f5f6400-108a-11e9-8645-e59ebe7ddff1.jpg)
![img_3813](https://user-images.githubusercontent.com/16299010/50718722-7f5f6400-108a-11e9-9517-3e33bb595f72.jpg)

**Comment by Dmonero** [comment]
Hi,  Have you tried loading the wallet from file instead of creating a new harware wallet?

**Comment by Dmonero** [comment]
I can't see the words in my XMR Hard wallet either.  I think you once you restore the entire Ledger, the Monero account used by the ledger is supposed to be the same even if you start a new harware wallet from the device.  Unfortunately or fortunatly, I haven't done this yet to confirm if it works.  Why don't you try to open the other wallets in your Monero folder, the normal one use by the desktop. I accidentally send some coin to mine by mistake and freaked out for a little bit.  Could be there. 

 When you open the wallet is everything syncing correctly? Showing sync complete?

  I created multiple new hardware wallets from the ledger and they all had the same address. Just I opened them at different points in the blockchain which seemed to help my issues with syncing the balance available.  

Note: I sync with ledger live with Ledger nano in the manage section each time before entering the Monero app on the device.  Then open Monero on the the Ledger Nano.  After all that is done then I open monero on the desktop.  It seems to work the best when done in that order. 

If you are looking for a particular transaction try creating new wallets in the blockchain around when the transaction was made.   You can get that info from the sending account.  Good luck

**Comment by challal** [comment]
thank you
i try every thing i waiting monero blokchain to sync 3 days, after this i open new wallet with my ledger i see my balance is 0 XMR,and reinstall my monero app in my ledger with ledger live i get new address every time i go to get 25 word to open wallet with him like in photo nothing show in my nano
haw can get this 25 word with my 24 word of ledger ?

**Comment by Dmonero** [comment]
From what I understand you can't recover just one part of the ledger.  I don't understand why you would be getting a new address each time you installed Monero.  That doesn't make sense.  The only recover options for the ledger is below.  If that was my Monero account with alot of money in there, I wouldn't recover the ledger unless I had a 2nd ledger nano to try the recovery on.  Because you should be able to simply duplicate the device from the 24 word phrase.  

https://support.ledger.com/hc/en-us/articles/360005434914-Restore-from-recovery-phrase.

I haven't done this yet but am keen to try it now that you've had trouble.
