### ISSUE TITLE
Wrong Device Status: SW=6e00, EXPECT=9000, MASK=ffff

### ISSUE THREAD

**Issue by NullVoxPopuli** [LedgerHQ/ledger-app-monero#33]
error:
```
2019-03-09 15:17:10.351	    7f9d2b82c7c0	ERROR	device.ledger	src/device/device_ledger.cpp:319	Wrong Device Status : SW=6e00 (EXPECT=9000, MASK=ffff)
```

I _just_ installed the Monero GUI app (0.14.0.0)

I got the error both with the Monero app open and closed.

Ledger Live works fine.
I even uninstalled and re-installed the Monero app on my ledger.
(though, when re-installing, apparently I didn't have enough space, so I also uninstalled another app)

after re-installing, and trying both new/restore wallet, same error.
opening the Monero app, and I get this error:
```
2019-03-09 15:25:13.541	    7f9d2b82c7c0	ERROR	device.io	src/device/device_io_hid.cpp:82	Unable to enumerate device 11415:11415: NULL device
```

I even tried re-plugging-in the ledger.

I'm using:
 - Ubuntu 18.04
 - Ledger Nano S

**Comment by NullVoxPopuli** [comment]
Apparently the Restore Height is _not_ optional.

I used: 1765000

**Comment by jaapio20** [comment]
I have the same problem. How did you come to a solution?

**Comment by krtschmr** [comment]
so what's the fix?

**Comment by RieGo** [comment]
same problem here. both with nano s and nano x
anyone found a solution yet?

**Comment by nandesco** [comment]
just simple,open monero gui 0,14 with administrator privileges. Works like a charm!

**Comment by cslashm** [comment]
This is very strange, 6e00 means e
- either your Monero app is not launched
- either Live runs: close it, and restart MoneroApp
- or you have a mismatch version between Nano App  and Monero client

**Comment by TheHeroBrine422** [comment]
You might need to update the monero app on your ledger. Mine was out dated (I think 1.1.x) and when i updated the firmware of my ledger and the monero app it worked.

**Comment by krtschmr** [comment]
i can add: i had to update twice. 
did first (to an older version?) , then there was no more update available. restarted everything and then there was another update. after installing the second one, the ledger was working as expected
