### ISSUE TITLE
Wrong Device Status : SW=6914 (EXPECT=9000, MASK=ffff) when trying to churn to own "4" address.

### ISSUE THREAD

**Issue by pricead** [LedgerHQ/ledger-app-monero#37]
I'm getting the error **Wrong Device Status : SW=6914 (EXPECT=9000, MASK=ffff)** both when trying to use Monero OSX v0.14.0.2-release and also with Monerujo 1.11.5. The error occurs when trying to send to a regular "4" address (more specifically my own address) after confirming the transaction on the device.

[Error is referenced here](https://github.com/monero-project/monero/issues/5228) but seems to be more of an issue with Ledger's app so opening issue on this project.

Further details in case it's helpful:
Ledger Nano S is fully up to date (running firmware v1.5.5)
Ledger Monero app is v1.2.0
Computer is a MacBook Pro (2018) running MacOS 10.14.3
Android device is running Android 9.0 Pie and Monerujo 1.11.5

**Comment by lacksfish** [comment]
It could be related to recent changes to the payment id requirements, if it is not provided. I'm still not sure how, but that's the only thing where the main address is different.

**Comment by pricead** [comment]
@lacksfish I added more details to my original post. No payment ID was specified as I was attempting to send to my own address.

**Comment by pricead** [comment]
> It could be related to recent changes to the payment id requirements, if it is not provided.

Further tests I've done seem to only have a problem when churning to your own address. Sending to a different "4" address were processed fine.

**Comment by cslashm** [comment]
A new app (1.3.0) will be  soon (with next 0.14... release) available. It should fix it.

**Comment by cslashm** [comment]
@pricead Is it fixe for you with 1.3.1?

**Comment by pricead** [comment]
@cslashm yes, fixed now! Thank you.
