### ISSUE TITLE
wrong device status SW=6e00 ( EXPECT=9000, MASK=ffff )

### ISSUE THREAD

**Issue by jaapio20** [LedgerHQ/ledger-app-monero#39]
I recently updated my wallet to 0.14 from 0.13 because my transaction was not working. I did a transaction, what is still stuck in the old chain in the version 0.13.
 I can't go into my updated monero ledger wallet (0.14). If i try to get in there is a error called: wrong device status SW=6e00 (EXPECT=9000, MASK=ffff). I updated my ledger live but that didn't work
How can I fix this problem?

(Im using macOS Sierra 10.12.6.)

**Comment by cslashm** [comment]
check you are 0.14.0.2 client and 1.2.2 application

**Comment by jaapio20** [comment]
@cslashm thanks you, it worked!! :)

**Comment by lacksfish** [comment]
@jaapio20 Perhaps close the issue then :) For tidiness reasons.
