### ISSUE TITLE
Ledger Nano X support

### ISSUE THREAD

**Issue by LedgerUser1** [LedgerHQ/ledger-app-monero#41]
Ledger Nano X is currently not supported.

**Comment by johnalanwoods** [comment]
Not sure what’s required for PR. Would suggest you don’t invest too much time.

**Comment by GoodEn0ugh** [comment]
My plan was to use the X for a hot wallet of sorts, but it appears Monero isn't supported at all. Would love to see this added in!

**Comment by LedgerUser1** [comment]
It will be added in the next Monero Gui update.
