### ISSUE TITLE
Error: failed to generate new wallet: Wrong Device Status : SW=6930 (EXPECT=9000, MASK=ffff)

### ISSUE THREAD

**Issue by apxs94** [LedgerHQ/ledger-app-monero#45]
Currently using CLI 0.14.1.2 on Mac OSX - 10.14.5 (Mojave) 
Ledger has Monero 1.3.1 installed on it. 
Daemon is running and fully synced. 
Ledger is plugged in and unlocked (confirmed working with Ledger Live). 
Monero app is open on Ledger.

When I try to either open a monero wallet, or generate a new one, I get the error:
Error: failed to load wallet: Wrong Device Status : SW=6930 (EXPECT=9000, MASK=ffff). 

Example of command I'm running:
./monero-wallet-cli --generate-from-device exampleWallet --subaddress-lookahead 2:5

Any suggestions as to what I might be doing wrong?

**Comment by cslashm** [comment]
duplicate issue #43

**Comment by apxs94** [comment]
Thanks for the reference @cslashm 

Is there a way that we can turn the error message:
`Error: failed to load wallet: Wrong Device Status : SW=6930 (EXPECT=9000, MASK=ffff)`

Into something like "This version of Monero is not supported, please use version xxx"?

Or, if that's not possible, a similar solution?

This would help avoid unnecessary confusion/frustration/anxiety. Currently the existing error message is unintelligible to myself, and no doubt others.

**Comment by cslashm** [comment]
Yes I will add error message in 1.4.0 on the device.
For this one I will make quick fixe in order to release this week

**Comment by apxs94** [comment]
Thanks @cslashm - error messages with more info will help a lot.
Thanks for the reply & all your hard work.

**Comment by Jay991** [comment]
Hi I'm running on monero-gui-v0.15.0.1 
Update the lastest ledger app and Monero App on ledger nano s 
Also enable developer mode 
Still receiving this error when attempting to connect my wallet: 
Error: failed to generate new wallet: Wrong Device Status : SW=6930 (EXPECT=9000, MASK=ffff)
