### ISSUE TITLE
Wrong Device Status : SW=6e00 (EXPECT=9000, MASK=FFFF)

### ISSUE THREAD

**Issue by JohnZettler** [LedgerHQ/ledger-app-monero#48]
Hi community - I am unable to `Create a new wallet from hardware`, using my Ledger Nano S.

Can anyone help?  My set-up below. 

## My set-up
- **OS**: Windows 10 (x64) Education (similar to Enterprise)
- **Monero wallet**: GUI wallet for Windows, release Carbon Chamaeleon, version 0.15.0.1
- **Ledger firmware**: 1.5.5
- **Monero Ledger app**: 1.3.1

**Comment by tficharmers** [comment]
Your Monero Ledger app needs updating to 1.4.x. You might need to check ‘Developer mode’ in Ledger’s desktop app in order to see 1.4.x.

(this is just from my memory so might not be accurate)

**Comment by JohnZettler** [comment]
Hmm...okay.  I have turned `Developer Mode` on previously (in order to download the Cosmos (ATOM) Ledger app).  

Even with `Developer Mode` on, the only Monero Ledger app shown in my Ledger Live UI is the 1.3.1 version (already installed).

**Comment by pricead** [comment]
> Hmm...okay. I have turned `Developer Mode` on previously (in order to download the Cosmos (ATOM) Ledger app).
> 
> Even with `Developer Mode` on, the only Monero Ledger app shown in my Ledger Live UI is the 1.3.1 version (already installed).


You need to update your Nano S firmware to 1.6.

**Comment by JohnZettler** [comment]
> > Hmm...okay. I have turned `Developer Mode` on previously (in order to download the Cosmos (ATOM) Ledger app).
> > Even with `Developer Mode` on, the only Monero Ledger app shown in my Ledger Live UI is the 1.3.1 version (already installed).
> 
> You need to update your Nano S firmware to 1.6.

👍 Got it.  Will do and will report back.  Thank you!

**Comment by cslashm** [comment]
For 0.15.0.x series you need firmware 1.6 and application 1.4.**_2_**

**Comment by sdsoft1976** [comment]
Please help.
Everything worked fine, got the same problem.
Version Monero GUI Wallet 0.15.0.4 , updated to 0.17.1.4 - problem still exists
Frimfare Version Ledger nano s 1.6.0
Monero Ledger app 1.6.0
Regards Denis

**Comment by pricead** [comment]
> Please help.
> Everything worked fine, got the same problem.
> Version Monero GUI Wallet 0.15.0.4 , updated to 0.17.1.4 - problem still exists
> Frimfare Version Ledger nano s 1.6.0
> Monero Ledger app 1.6.0
> Regards Denis

Update your Ledger's Monero app.

**Comment by sdsoft1976** [comment]
> > Пожалуйста помоги. 
> > Все работало нормально, возникла такая же проблема. 
> > Версия Monero GUI Wallet 0.15.0.4, обновлена ​​до 0.17.1.4 - проблема все еще существует 
> > Frimfare Версия Ledger nano s 1.6.0 
> > Приложение Monero Ledger 1.6.0 
> > С уважением, Денис
> 
> Обновите приложение Monero в Ledger.

Thanks.
Which version is current?

**Comment by pricead** [comment]
> > > Пожалуйста помоги.
> > > Все работало нормально, возникла такая же проблема.
> > > Версия Monero GUI Wallet 0.15.0.4, обновлена ​​до 0.17.1.4 - проблема все еще существует
> > > Frimfare Версия Ledger nano s 1.6.0
> > > Приложение Monero Ledger 1.6.0
> > > С уважением, Денис
> > 
> > 
> > Обновите приложение Monero в Ledger.
> 
> Thanks.
> Which version is current?

I think it's 1.7.4 now:

https://www.reddit.com/r/monerosupport/comments/jdtz9s/_/g9axspg
