### ISSUE TITLE
minexmr.com Payment not working

### ISSUE THREAD

**Issue by Soliver84** [LedgerHQ/ledger-app-monero#51]
Hello my minexmr.com:

![image](https://user-images.githubusercontent.com/11579411/72195212-804f7200-3411-11ea-9d10-72432e0ecd27.png)

Total Paid: 2.413413480000 XMR not Working

Please check what's going on.

Transaction Hash: https://blox.minexmr.com/tx/2a4a731c38d8b3c825032195b2b467007ef60bcf8d29f982a5bef3e15dd7aeac

![image](https://user-images.githubusercontent.com/11579411/72195321-010e6e00-3412-11ea-8447-5a1d60ee9e6c.png)

![image](https://user-images.githubusercontent.com/11579411/72195345-197e8880-3412-11ea-8bac-6442ef7d54e9.png)

NEW STAND:11.01.2020 2:00:

MY Ledger Nano X MONERO WALLET:
42Ak5EWJAUi7Wz2XASwLfdb17jQppZtk4UVbNpoZW1rTctHaBpTdhHkZAhUtL4jmv5jamxEBLDVHbQeSdfAWkXkEQGrXBn4

WALLET:

![image](https://user-images.githubusercontent.com/11579411/72196289-6a44b000-3417-11ea-9e5c-57a864e1c41c.png)

![image](https://user-images.githubusercontent.com/11579411/72195357-28653b00-3412-11ea-8b97-57c4245830c4.png)

![image](https://user-images.githubusercontent.com/11579411/72196069-079ee480-3416-11ea-8653-c3e112e2aff1.png)

https://www.file-upload.net/download-13854232/mineXMR-MoneroBlockchainExplorerOLDTransaction.rar.html

https://www.file-upload.net/download-13854233/mineXMR-MoneroBlockchainExplorerNEWTansackton.zip.html

Please Help Me

Thanks for watching

**Comment by Soliver84** [comment]
Hello?

**Comment by pricead** [comment]
This really isn't the correct place for your question. I suggest posting your problem on reddit.com/r/monero or reddit.com/r/monerosupport.

**Comment by dginovker** [comment]
The user's wallet isn't in sync here. Issue can be closed.

![image](https://user-images.githubusercontent.com/32943174/72210307-46b94e00-3487-11ea-8b1a-793871494654.png)

**Comment by Soliver84** [comment]
not:
![image](https://user-images.githubusercontent.com/11579411/72210352-49816680-34ba-11ea-8722-6910f60365cb.png)

**Comment by Soliver84** [comment]
Ver:
![image](https://user-images.githubusercontent.com/11579411/72210420-71bd9500-34bb-11ea-8b96-9c68a7ce4ebc.png)

**Comment by cslashm** [comment]
@Soliver84 is your pb solved?

**Comment by cslashm** [comment]
no more activity/answer
