### ISSUE TITLE
Invalid status 6f42 (Unknown reason) with firmware 1.6.0

### ISSUE THREAD

**Issue by ph4r05** [LedgerHQ/ledger-app-monero#53]
Hi @cslashm !

I wanted to compile this version and install it on Ledger Nano S v1.6.0 but the 

```c
 cx_aes(&G_monero_vstate.spk, CX_ENCRYPT|CX_CHAIN_CBC|CX_LAST|CX_PAD_NONE,
         buffer, len,
         G_monero_vstate.io_buffer+G_monero_vstate.io_offset, len);
```

Causes an error:  Invalid status 6f42 (Unknown reason)

If I switch to `IODUMMYCRYPT` everything works fine. Any idea what could be the problem with the new firmware?

Thanks!

**Comment by cslashm** [comment]
Hi,

AES/RSA (ie strong encryption) is not available by default on device. This is because of french  cryptography  exports laws.

**Comment by ph4r05** [comment]
Aah OK, thanks for info!

I've made some custom modifications so the app can be deployed to 1.6.0 firmware.

**Comment by ph4r05** [comment]
Aah OK, thanks for info!

I've made some custom modifications so the app can be deployed to 1.6.0 firmware.

The changes are here: https://github.com/ph4r05/blue-app-monero/commit/edb5e713e8ac42dd80a7a8b52803a33f118cc153

Basically I've added custom lightweight AES-CBC implementation in C which is used instead of `cx_aes` if `IOCUSTOMCRYPT` is defined. This works well.

I've also added a workaround for missing glyphs like `C_badge_back` just by setting glyphs to NULL.

**Comment by mdPlusPlus** [comment]
> Hi,
> 
> AES/RSA (ie strong encryption) is not available by default on device. This is because of french cryptography exports laws.

Can we get a source for this statement? This seems like a statement straight from the US of the 1990s.
